import { ArrowRight, CheckCircle2, CircleDollarSign, Coins, GitBranch, LockKeyhole, MapPin, Network, Route, Sprout, Store, TreePine } from "lucide-react";
import Link from "next/link";

const phases = [
  { number: "01", status: "Shipped", title: "ContextKit App Launch", subtitle: "Foundation", icon: Sprout, tone: "mint", side: "left", text: "Public context APIs, dashboard accounts, credits, x402 endpoints, SDK, and a real agent-memory product surface.", outcome: "A usable context layer for agents." },
  { number: "02", status: "Shipped", title: "MCP V1", subtitle: "Distribution", icon: Network, tone: "aqua", side: "right", text: "Remote Streamable HTTP MCP with OAuth, scoped credentials, account credits, and agent tools for summary, handoff, profile, and token work.", outcome: "ContextKit enters coding-agent workflows." },
  { number: "03", status: "You are here", title: "Token Launch", subtitle: "Coordination layer", icon: Coins, tone: "amber", side: "left", current: true, text: "Launch the network token with a clear utility narrative: it is not the x402 payment rail. USDC remains the predictable compute currency.", outcome: "A coordination asset, not a fake subscription." },
  { number: "04", status: "Planned", title: "MCP V2: Experience Recorder", subtitle: "Capture", icon: GitBranch, tone: "coral", side: "right", text: "Let agents record signed experience artifacts: what they tried, constraints, outcome, confidence, and reusable operating context.", outcome: "Experience becomes portable infrastructure." },
  { number: "05", status: "Planned", title: "Agent Experience Marketplace", subtitle: "Exchange", icon: Store, tone: "aqua", side: "left", text: "Agents buy verified experience packs from each other through Bankr x402. Payments stay in USDC so pricing remains clear and executable.", outcome: "A real market for reusable agent knowledge." },
  { number: "06", status: "Vision", title: "ContextKit Network", subtitle: "Security + reputation", icon: TreePine, tone: "mint", side: "right", text: "Token staking, creator reputation, quality collateral, fee discounts, premium pools, and shared team Memory Vaults secure the marketplace.", outcome: "Token demand follows useful network behavior." }
] as const;

export const metadata = {
  title: "Roadmap",
  description: "The ContextKit roadmap from agent memory infrastructure to a token-staked experience network."
};

export default function RoadmapPage() {
  return (
    <main className="roadmap-stage relative min-h-screen overflow-hidden px-5 py-8 md:py-10">
      <div className="roadmap-grain pointer-events-none absolute inset-0" />
      <div className="roadmap-canopy pointer-events-none absolute -right-56 top-12 h-[44rem] w-[44rem] rounded-full" />
      <div className="relative mx-auto max-w-7xl">
        <section className="roadmap-hero overflow-hidden rounded-[1.75rem] border border-white/[0.14]">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.18em] text-white/45 sm:px-7"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-mint" /> ContextKit route map</span><span>launch → network</span><span className="text-mint">6 stops</span></div>
          <div className="grid gap-8 p-7 sm:p-10 lg:grid-cols-[1.08fr_0.92fr] lg:p-14"><div><p className="font-mono text-[11px] uppercase tracking-[0.2em] text-mint">Protocol roadmap</p><h1 className="roadmap-title mt-6 max-w-4xl text-balance text-5xl font-semibold leading-[0.88] tracking-[-0.07em] text-white sm:text-6xl lg:text-7xl">A straight route from memory to an <span className="text-mint">agent economy.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/65">Every stop must earn the next one. First the product works. Then agents carry experience. Then a market needs trust, collateral, and a coordination layer.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#map" className="inline-flex h-10 items-center gap-2 rounded-lg bg-mint px-4 text-sm font-semibold text-ink transition hover:bg-white">Open route map <ArrowRight className="h-4 w-4" /></Link><Link href="/mcp-guide" className="inline-flex h-10 items-center gap-2 rounded-lg border border-white/15 bg-white/[0.035] px-4 text-sm text-white/75 transition hover:border-mint/45 hover:text-white">MCP today <ArrowRight className="h-4 w-4" /></Link></div></div><div className="roadmap-specimen relative min-h-[310px] overflow-hidden rounded-[1.35rem] border border-mint/20 p-6"><div className="roadmap-map-mark absolute inset-0" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.16em] text-white/45"><span>Route status</span><span>03 / active</span></div><div className="flex items-center gap-5"><span className="relative grid h-20 w-20 place-items-center rounded-full border border-amber/50 bg-amber/[0.08] text-amber shadow-[0_0_0_12px_rgba(246,211,101,0.04)]"><MapPin className="h-8 w-8" /><i className="roadmap-location-pulse" /></span><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-amber">Current stop</p><p className="mt-2 text-2xl font-semibold text-white">Token Launch</p></div></div><div className="max-w-xs border-l border-mint/50 pl-4 text-sm leading-6 text-white/65">The token becomes useful only after agents need a trusted way to publish, discover, and guarantee experience.</div></div></div></div>
        </section>

        <section id="map" className="mt-16 scroll-mt-24"><div className="flex flex-col gap-4 border-b border-line pb-7 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-mint">Route map</p><h2 className="mt-3 max-w-3xl text-3xl font-semibold tracking-[-0.04em] text-white md:text-5xl">The road ahead, stop by stop.</h2></div><div className="flex flex-wrap gap-3 font-mono text-[10px] uppercase tracking-[0.14em]"><span className="text-mint">● shipped</span><span className="text-amber">● current</span><span className="text-white/45">○ planned</span></div></div>
          <ol className="roadmap-map mt-12">{phases.map((phase) => { const Icon = phase.icon; const isCurrent = "current" in phase && phase.current; const accent = phase.tone === "mint" ? "text-mint border-mint/25 bg-mint/[0.06]" : phase.tone === "aqua" ? "text-aqua border-aqua/25 bg-aqua/[0.06]" : phase.tone === "amber" ? "text-amber border-amber/25 bg-amber/[0.06]" : "text-coral border-coral/25 bg-coral/[0.06]"; return <li key={phase.number} className={`roadmap-stop roadmap-stop--${phase.side}`}><article className="roadmap-branch"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><span className={`font-mono text-xs ${accent.split(" ")[0]}`}>{phase.number}</span><span className={`rounded-full border px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.15em] ${accent}`}>{phase.status}</span></div><p className="mt-5 font-mono text-[10px] uppercase tracking-[0.17em] text-white/40">{phase.subtitle}</p><h3 className="mt-2 text-2xl font-semibold tracking-[-0.035em] text-white">{phase.title}</h3></div><span className={`grid h-10 w-10 place-items-center rounded-xl border ${accent}`}><Icon className="h-4 w-4" /></span></div><p className="mt-5 leading-7 text-white/62">{phase.text}</p><div className="mt-5 flex items-center gap-3 border-t border-line pt-4"><Route className={`h-4 w-4 ${accent.split(" ")[0]}`} /><p className="text-sm text-white/70">{phase.outcome}</p></div></article><span className={`roadmap-stop-marker ${accent} ${isCurrent ? "roadmap-stop-marker--current" : ""}`}><Icon className="h-4 w-4" />{isCurrent ? <i className="roadmap-stop-pulse" /> : null}</span></li>; })}</ol>
        </section>

        <section className="mt-16 grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><div className="rounded-[1.35rem] border border-amber/25 bg-amber/[0.055] p-6 sm:p-7"><div className="grid h-11 w-11 place-items-center rounded-xl border border-amber/30 bg-amber/[0.08]"><CircleDollarSign className="h-5 w-5 text-amber" /></div><p className="mt-6 font-mono text-[10px] uppercase tracking-[0.18em] text-amber">Token demand principle</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-white">Keep payment stable. Make trust scarce.</h2><p className="mt-4 leading-7 text-white/60">USDC/x402 remains the compute payment rail. The token earns demand by securing quality, lowering friction, and unlocking better network behavior.</p></div><div className="grid gap-px overflow-hidden rounded-[1.35rem] border border-line bg-line sm:grid-cols-2"><Thesis title="Stake to publish" text="Creators bond tokens behind experience packs, signaling they stand behind what agents buy." /><Thesis title="Earn reputation" text="Useful, reused experience increases creator standing. Spam and low-quality artifacts lose discoverability." /><Thesis title="Unlock better economics" text="Stakers receive execution priority, fee discounts, premium pools, or team Memory Vault capacity." /><Thesis title="Secure the market" text="Token collateral makes quality and dispute resolution part of the protocol, not just a social promise." /></div></section>

        <section className="mt-16 flex flex-col gap-5 rounded-[1.35rem] border border-mint/20 bg-mint/[0.06] p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-mint/25 bg-mint/[0.1]"><LockKeyhole className="h-5 w-5 text-mint" /></span><div><h2 className="text-xl font-semibold text-white">Utility before speculation.</h2><p className="mt-2 max-w-2xl leading-7 text-white/58">No yield promises, no forced token payment, no empty governance theater. Each token feature should follow proven marketplace usage and appropriate legal review.</p></div></div><Link href="/contact-dev" className="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-lg bg-mint px-4 text-sm font-semibold text-ink transition hover:bg-white">Shape the network <ArrowRight className="h-4 w-4" /></Link></section>
      </div>
    </main>
  );
}

function Thesis({ title, text }: { title: string; text: string }) {
  return <article className="bg-carbon/90 p-5"><CheckCircle2 className="h-4 w-4 text-mint" /><h3 className="mt-4 text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{text}</p></article>;
}
