import { ArrowRight, CheckCircle2, CircleDollarSign, Coins, GitBranch, LockKeyhole, Network, Sprout, Store, TreePine } from "lucide-react";
import Link from "next/link";

const phases = [
  { number: "01", status: "Shipped", title: "App Launch", subtitle: "Foundation", icon: Sprout, tone: "mint", text: "Public APIs, x402 endpoints, SDK, dashboard accounts, credits, and a usable memory product.", outcome: "Context layer is live." },
  { number: "02", status: "Shipped", title: "MCP V1", subtitle: "Distribution", icon: Network, tone: "aqua", text: "Streamable HTTP MCP with OAuth, scoped credentials, and agent tools across the IDE surface.", outcome: "Agents can use ContextKit." },
  { number: "03", status: "You are here", title: "MCP V2", subtitle: "Verified Repositories", icon: GitBranch, tone: "coral", current: true, text: "Agents compile proven work, attach source, tests, examples, config, and lockfiles, then push immutable content-addressed versions.", outcome: "Evidence-backed repositories become safely cloneable." },
  { number: "04", status: "Planned", title: "Token Launch", subtitle: "Coordination", icon: Coins, tone: "amber", text: "A utility-first coordination asset. USDC remains the predictable x402 compute currency.", outcome: "Token follows proven utility." },
  { number: "05", status: "Planned", title: "Verified Skill Market", subtitle: "Exchange", icon: Store, tone: "aqua", text: "Agents discover manifests, pay through Bankr x402, and clone complete checksum-verified source repositories with clear USDC pricing.", outcome: "Executable knowledge becomes tradeable." },
  { number: "06", status: "Vision", title: "ContextKit Network", subtitle: "Trust", icon: TreePine, tone: "mint", text: "Staking, reputation, collateral, premium pools, and shared Memory Vaults secure the exchange.", outcome: "Utility compounds with usage." }
] as const;

export const metadata = {
  title: "Roadmap",
  description: "The ContextKit roadmap from agent memory infrastructure to a token-secured verified skill network."
};

export default function RoadmapPage() {
  return (
    <main className="roadmap-stage relative min-h-screen overflow-hidden px-5 py-6 md:py-8">
      <div className="roadmap-grain pointer-events-none absolute inset-0" />
      <div className="roadmap-canopy pointer-events-none absolute -right-56 top-0 h-[36rem] w-[36rem] rounded-full" />
      <div className="relative mx-auto max-w-7xl">
        <section className="roadmap-hero overflow-hidden rounded-[1.6rem] border border-white/[0.14]">
          <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 px-5 py-3 font-mono text-[10px] uppercase tracking-[0.18em] text-white/45 sm:px-7"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-mint" /> ContextKit route map</span><span>launch → network</span><span className="text-mint">6 stops</span></div>
          <div className="p-6 sm:p-8 lg:p-10">
            <div className="roadmap-overview"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-mint">Protocol roadmap</p><h1 className="mt-4 max-w-3xl text-balance text-4xl font-semibold leading-[0.92] tracking-[-0.065em] text-white sm:text-5xl lg:text-6xl">From live memory tools to a <span className="text-mint">trusted agent network.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/62">The order matters: prove the context layer, distribute it through MCP, compile tested portable skills, then launch token utility around real demand.</p></div><div className="roadmap-current"><span className="relative grid h-12 w-12 place-items-center rounded-full border border-coral/50 bg-coral/[0.08] text-coral"><GitBranch className="h-5 w-5" /><i className="roadmap-location-pulse" /></span><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-coral">Current location</p><p className="mt-1 text-lg font-semibold text-white">03 / MCP V2</p></div></div></div>

            <ol className="roadmap-rail mt-8">{phases.map((phase) => { const Icon = phase.icon; const isCurrent = "current" in phase && phase.current; const accent = phase.tone === "mint" ? "text-mint border-mint/25 bg-mint/[0.06]" : phase.tone === "aqua" ? "text-aqua border-aqua/25 bg-aqua/[0.06]" : phase.tone === "amber" ? "text-amber border-amber/25 bg-amber/[0.06]" : "text-coral border-coral/25 bg-coral/[0.06]"; return <li key={phase.number} className="roadmap-rail-stop"><span className={`roadmap-rail-marker ${accent} ${isCurrent ? "roadmap-rail-marker--current" : ""}`}><Icon className="h-3.5 w-3.5" />{isCurrent ? <i className="roadmap-stop-pulse" /> : null}</span><article className={`roadmap-rail-card ${isCurrent ? "roadmap-rail-card--current" : ""}`}><div className="flex items-center justify-between gap-2"><span className={`font-mono text-[10px] ${accent.split(" ")[0]}`}>{phase.number}</span><span className={`rounded-full border px-2 py-1 font-mono text-[8px] uppercase tracking-[0.13em] ${accent}`}>{phase.status}</span></div><p className="mt-5 font-mono text-[9px] uppercase tracking-[0.16em] text-white/40">{phase.subtitle}</p><h2 className="mt-1.5 text-lg font-semibold tracking-[-0.035em] text-white">{phase.title}</h2><p className="mt-3 text-sm leading-5 text-white/58">{phase.outcome}</p></article></li>; })}</ol>
          </div>
        </section>

        <section id="details" className="mt-12 scroll-mt-24"><div className="flex flex-col gap-3 border-b border-line pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-mint">Milestone detail</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.045em] text-white">What each stop unlocks.</h2></div><Link href="/mcp-guide" className="inline-flex items-center gap-2 text-sm text-mint transition hover:text-white">Use MCP today <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{phases.map((phase) => { const Icon = phase.icon; const isCurrent = "current" in phase && phase.current; const tone = phase.tone === "mint" ? "text-mint border-mint/25 bg-mint/[0.05]" : phase.tone === "aqua" ? "text-aqua border-aqua/25 bg-aqua/[0.05]" : phase.tone === "amber" ? "text-amber border-amber/25 bg-amber/[0.05]" : "text-coral border-coral/25 bg-coral/[0.05]"; return <article key={phase.number} className={`roadmap-detail-card ${isCurrent ? "roadmap-detail-card--current" : ""}`}><div className="flex items-start justify-between gap-4"><span className={`grid h-10 w-10 place-items-center rounded-xl border ${tone}`}><Icon className="h-4 w-4" /></span><span className={`rounded-full border px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.14em] ${tone}`}>{phase.status}</span></div><p className="mt-5 font-mono text-[10px] uppercase tracking-[0.16em] text-white/42">{phase.number} / {phase.subtitle}</p><h3 className="mt-2 text-xl font-semibold tracking-[-0.035em] text-white">{phase.title}</h3><p className="mt-3 text-sm leading-6 text-white/60">{phase.text}</p></article>; })}</div></section>

        <section className="mt-12 grid gap-4 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[1.3rem] border border-amber/25 bg-amber/[0.055] p-6"><CircleDollarSign className="h-5 w-5 text-amber" /><p className="mt-5 font-mono text-[10px] uppercase tracking-[0.18em] text-amber">Token demand principle</p><h2 className="mt-3 text-2xl font-semibold tracking-[-0.04em] text-white">Keep payment stable. Make trust scarce.</h2><p className="mt-3 leading-7 text-white/60">USDC/x402 stays the compute rail. The token earns demand only by securing quality and reducing useful network friction.</p></div><div className="grid gap-px overflow-hidden rounded-[1.3rem] border border-line bg-line sm:grid-cols-2"><Thesis title="Stake to publish" text="Creators bond tokens behind verified skills." /><Thesis title="Earn reputation" text="Successful installs improve skill discovery." /><Thesis title="Unlock economics" text="Staking can unlock fee discounts and private registries." /><Thesis title="Secure exchange" text="Collateral supports quality and disputes." /></div></section>

        <section className="mt-12 flex flex-col gap-5 rounded-[1.3rem] border border-mint/20 bg-mint/[0.06] p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-mint/25 bg-mint/[0.1]"><LockKeyhole className="h-5 w-5 text-mint" /></span><div><h2 className="text-xl font-semibold text-white">Utility before speculation.</h2><p className="mt-2 max-w-2xl leading-7 text-white/58">No forced token payments and no empty governance theater. Every token feature must follow product usage, marketplace demand, and legal review.</p></div></div><Link href="/contact-dev" className="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-lg bg-mint px-4 text-sm font-semibold text-ink transition hover:bg-white">Shape the network <ArrowRight className="h-4 w-4" /></Link></section>
      </div>
    </main>
  );
}

function Thesis({ title, text }: { title: string; text: string }) {
  return <article className="bg-carbon/90 p-5"><CheckCircle2 className="h-4 w-4 text-mint" /><h3 className="mt-3 text-base font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{text}</p></article>;
}
